### PR TITLE
Migration to NUnit3

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@rprouse Hot to say to `nunit.console` runner to print about passed tests during execution?
https://travis-ci.org/sergey-tihon/SwaggerProvider/builds/110445230#L1371

**Comment by sergey-tihon** [comment]
@CharliePoole Could you help plz?

**Comment by CharliePoole** [comment]
I'm not sure what you are asking.

Are you trying to get the names of all tests to be listed as they run? You can do that by using --labels:All on the command line.

**Comment by sergey-tihon** [comment]
Thank you @CharliePoole 
It look exactly like what I need.

**Comment by sergey-tihon** [comment]
@CharliePoole Is possibly to print full test names when run with `--labels:All` parameter ?
After string truncation test names are not informative at all =(

image

**Comment by CharliePoole** [comment]
Technically, those are the full test names. :-)

That is, NUnit 3.0 truncates strings when creating test names. You can change the degree of truncation by setting the name of the test using the TestName named parameter of TestCaseAttribute.

The names of tests are generated using a pattern. The default is `{m}{a:40}` which translates to "the method name followed by an argument list in parentheses, truncating the args to 50.

For your particular test, try something like `{m}{a:80}` or even `{m}{a}`.

Note that there is no way to set either the naming pattern or the default truncation length globally. We would consider a well-thought-out request to do this.

**Comment by CharliePoole** [comment]
Of course, as an alternative, you could leave the domain and path part of the URL out of the data and prefix using a constant in the code of the test. Depends on which is easier for you.

**Comment by sergey-tihon** [comment]
Thanks again @CharliePoole.
I generate tests dynamically, so i can generate `TestCaseData` instead of `string` and `SetName` manually. The perfect solution for me.
```fsharp
let toTestCase (url:string) =
    TestCaseData(url).SetName(sprintf "Parse schema %s" url)
```

**Pull request merged**
